### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by fishcharlie** [kcchu/atproto-firehose#1]
I'm running the following command, but nothing prints, it just hangs:

```
npx atproto-firehose bsky.social
```

It's almost like data isn't coming through or being received. Is this normal/expected?

**Comment by aql** [comment]
According to BlueSky's announcement, it seems good to use `bsky.network`.

Please take a look below.
https://atproto.com/blog/bgs-and-did-doc

**Comment by fishcharlie** [comment]
@aql Thanks so much! That worked. Just created a PR to fix that in the README: #2.
